FROM node:16-alpine

# Задать рабочую директорию
WORKDIR /home/ilovedocker/app

# Скопировать файл hello.sh в рабочую директорию
COPY hello.sh ./

# Задать скрипт в качестве команды запуска
CMD ["sh", "./hello.sh"]
